Update roadmap.rst
FirelyTeam/firely-docs-firely-server pull request #269
Opened 2023-03-27 17:32 UTC by alexzautke

2023-03-28 06:40 UTC, cknaap requested changes

2023-03-28 06:40 UTC, cknaap commented on releasenotes/roadmap.rst
> +* Azure Active Dirctory and Single Sign-on support in Firely Auth
```suggestion
* Azure Active Directory and Single Sign-on support in Firely Auth
```

2023-04-04 08:29 UTC, alexzautke commented
@cknaap Would you mind approving the PR?

2023-04-17 14:55 UTC, cknaap approved these changes

2023-04-17 15:12 UTC, merged