Document AutoProvisionFromSecurityGroup setting
FirelyTeam/firely-docs-firely-server pull request #519
Opened 2024-08-11 20:16 UTC by alexzautke

2024-08-15 13:24 UTC, Sieuwkje-firely requested changes

2024-08-15 13:24 UTC, Sieuwkje-firely commented on security/firely-auth/firely-auth-sso.rst
> +    Based on the ``AutoProvisionFromSecurityGroup`` setting it is possible to restrict the sign-up of users based on security groups defined in the SSO provider. The attribution of a user account to
Can you add documentation on this setting in this page as well?

https://docs.fire.ly/projects/Firely-Server/en/latest/security/firely-auth/firely-auth-settings.html#external-identity-providers

2024-08-15 13:24 UTC, Sieuwkje-firely commented on security/firely-auth/firely-auth-sso.rst
> +#. Optional: Expose the `groups <https://learn.microsoft.com/en-us/entra/identity-platform/optional-claims?tabs=appui#configure-groups-optional-claims>`_ in the ID token if the SSO auto-provisioning
Are there any considerations for the different types of group claims that can be exposed? There are for instance several options for the ID, Acces, and SAML types.

2024-08-27 08:50 UTC, Sieuwkje-firely approved these changes

2024-08-27 08:50 UTC, merged

2024-08-27 08:50 UTC, khristinalukanets approved these changes